server:
  port: 8085

spring:
  application:
    name: NotificationService
  rabbitmq:
    host: localhost
    port: 5673
    username: logiflow
    password: logiflow123

# Configuraci√≥n JWT (debe coincidir con AuthService)
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

logging:
  level:
    ec.edu.espe.NotificationService: DEBUG
    org.springframework.amqp: INFO
    org.springframework.web.socket: DEBUG
